version: '3.1'

services:

  produtos_api:
    image: popai
    restart: always
    ports:
      - 8080:8080
    environment:
      - URL_POSTGRES: db_produtos_api
      - URL_POSTGRES_PORT: 5432

    depends_on:
      - db_produtos_api

  db_produtos_api:

    contaniner_name: db_produtos_api

    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: produto-api
      POSTGRES_USER: produto-api
      POSTGRES_PASSWORD: admin

