#H2 database
# Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;
    name: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true